USE Szkola
/*
DELETE FROM KONIEC_ROKU
DELETE FROM UCZEN_W_KLASIE
DELETE FROM UCZEN
DELETE FROM PRZEDMIOT
DELETE FROM KLASA
*/

DROP TABLE IF EXISTS stg_wyniki;
DROP TABLE IF EXISTS stg_koniec_roku;
DROP TABLE IF EXISTS stg_uczen_w_klasie;
DROP TABLE IF EXISTS stg_uczen;
DROP TABLE IF EXISTS stg_przedmiot;
DROP TABLE IF EXISTS stg_klasa;