/*
DELETE FROM KONIEC_ROKU
DELETE FROM UCZEN_W_KLASIE
DELETE FROM UCZEN
DELETE FROM PRZEDMIOT
DELETE FROM KLASA
*/

DROP TABLE IF EXISTS KONIEC_ROKU;
DROP TABLE IF EXISTS UCZEN_W_KLASIE;
DROP TABLE IF EXISTS UCZEN;
DROP TABLE IF EXISTS PRZEDMIOT;
DROP TABLE IF EXISTS KLASA;